conky.config = {
  alignment = 'top_left',
  background = true,
  draw_shades = false,
  default_color = 'fbf1c7',
  color2 = 'a89984',
  cpu_avg_samples = 2,
  double_buffer = true,
  font = 'CaskaydiaCove Nerd Font Mono:size=8',
  gap_x = 24,
  gap_y = 16,
  minimum_width = 200,
  no_buffers = true,
  own_window = true,
  own_window_type = 'override',
  own_window_transparent = true,
  update_interval = 1.0,
  use_xft = true,
}
conky.text = [[
${voffset 0}$color2${font CaskaydiaCove Nerd Font Mono:size=16}${time %A}$font\
${voffset -16}$alignr$color${font CaskaydiaCove Nerd Font Mono:size=32}${time %e}$font
${voffset -16}$color${font CaskaydiaCove Nerd Font Mono:size=16}${time %b}$font\
${voffset 0} $color${font CaskaydiaCove Nerd Font Mono:size=16}${time %Y}$font$color$hr
#
${voffset 16}${goto 32}${color}CPU$alignr$cpu%
${voffset 4}${goto 32}$color2${top name 1}$alignr$color${top cpu 1}%
${goto 32}$color2${top name 2}$alignr$color${top cpu 2}%
${goto 32}$color2${top name 3}$alignr$color${top cpu 3}%
${goto 32}$color2${top name 4}$alignr$color${top cpu 4}%
${goto 32}$color2${top name 5}$alignr$color${top cpu 5}%
#
${voffset 16}${goto 32}${color}RAM$alignr$mem
${voffset 4}${goto 32}$color2${top_mem name 1}$alignr$color${top_mem mem_res 1}
${goto 32}$color2${top_mem name 2}$alignr$color${top_mem mem_res 2}
${goto 32}$color2${top_mem name 3}$alignr$color${top_mem mem_res 3}
${goto 32}$color2${top_mem name 4}$alignr$color${top_mem mem_res 4}
${goto 32}$color2${top_mem name 5}$alignr$color${top_mem mem_res 5}
#
${voffset 16}${goto 32}${color}Swap$alignr${swap} / ${swapfree}
# $alignr${execi 10000 awk -F= '/TION/ {print $2}' /etc/lsb-release |sed 's/"//g'} ${execi 10000 awk -F= '/EASE=/ {printf $2" "} /NAME/ {print $2}' /etc/lsb-release}
# ${color2}${alignr}${execi 1200 whoami}@${nodename}
${alignr}${color2}uptime: ${color}${uptime_short}
# ${color2}${alignr}kernel: ${color}${kernel}
]]
